name: Update Lists

on:
  push:
    paths:
      - '*.py'
      - 'requirements.txt'
      - 'dns_resolvers.yml'
      - '.github/workflows/update_lists.yml'
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true
          cache: 'pip'

      - name: Check Python3 Version
        run: python3 --version

#      - name: Run list_generator.sh
#        run: |
#          echo 'previos state ...'
#          wc -l ipv?_list.txt
#          chmod +x list_generator.sh
#          ./list_generator.sh
#          echo 'new state ...'
#          wc -l ipv?_list.txt

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Generating IP Lists
        run: python3 ./list_generator.py

      - name: Generating CIDR Lists
        run: python3 ./generate_cidr.py

      - name: Convert CIDR Lists to JSON
        run: python3 ./generate_singbox_json.py

      - name: Download Latest Sing-box
        run: |
          SINGBOX_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          wget -O sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/${SINGBOX_VERSION}/sing-box-${SINGBOX_VERSION#v}-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          chmod +x sing-box-${SINGBOX_VERSION#v}-linux-amd64/sing-box

      - name: Compile JSON Rules with Sing-box
        run: |
          SINGBOX_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          ./sing-box-${SINGBOX_VERSION#v}-linux-amd64/sing-box rule-set compile --output supercell.srs "supercell.json"

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ipv?_list.txt cidr?.txt supercell.srs supercell.json
          git commit -m 'Updated Lists [Automated]'
          git pull
          git push

      - name: Check diff
        run: git diff HEAD~1..HEAD
